# Generated by Django 5.2.17 on 2026-09-28 07:23

import django.core.validators
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=profiles.models.profile_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, JPEG, PNG and WEBP images are allowed.'), profiles.models.validate_image_size]),
        ),
    ]
